### PR TITLE
iOS-10212 update mi movistar tokens

### PR DESCRIPTION
**Pull request by WanaldinoTelefonica**
## 🎟️ **Jira ticket**
[IOS-10212](https://jira.tid.es/browse/IOS-10212)

## 🥅 **What's the goal?**
- Update MiMovistar tokens

## 🚧 **How do we do it?**
- make skin ref=production

## 🏑 **AppCenter build**
image

### CODE REVIEW

**Review by idenjoe — APPROVED** [review]

**Review by yceballost — CHANGES_REQUESTED** [review]
Hi guys!!

We need to make a little change in input fields (and select) to use `textActivated` instead of `controlActivated` token

This is to ensure accessibility in this type of texts

https://github.com/Telefonica/mistica-ios/blob/3bb09ac0309cdf1c72f981005f2a57ce3af05567/Sources/Mistica/Components/InputField/InputField.swift#L917

This is our ticket in the design side, sorry, I forgot to create ticket of this to you :(
https://github.com/Telefonica/mistica-design/issues/1733

**Comment by WanaldinoTelefonica** [comment]
> Hi guys!!
> 
> We need to make a little change in input fields (and select) to use `textActivated` instead of `controlActivated` token
> 
> This is to ensure accessibility in this type of texts
> 
> https://github.com/Telefonica/mistica-ios/blob/3bb09ac0309cdf1c72f981005f2a57ce3af05567/Sources/Mistica/Components/InputField/InputField.swift#L917
> 
> This is our ticket in the design side, sorry, I forgot to create ticket of this to you :( [Telefonica/mistica-design#1733](https://github.com/Telefonica/mistica-design/issues/1733)

Hi @yceballost can you check it again?

**Comment by yceballost** [comment]
> > Hi guys!!
> > We need to make a little change in input fields (and select) to use `textActivated` instead of `controlActivated` token
> > This is to ensure accessibility in this type of texts
> > https://github.com/Telefonica/mistica-ios/blob/3bb09ac0309cdf1c72f981005f2a57ce3af05567/Sources/Mistica/Components/InputField/InputField.swift#L917
> > 
> > This is our ticket in the design side, sorry, I forgot to create ticket of this to you :( [Telefonica/mistica-design#1733](https://github.com/Telefonica/mistica-design/issues/1733)
> 
> Hi @yceballost can you check it again?

I can't see screenshot with this state to confirm! but I will trust 😄

**Review by yceballost — APPROVED** [review]

**Pull request merged**
