### PR TITLE
feat(FontStyle): Wrong base sizes for presets 5, 9 and 10

### PR DESCRIPTION
**Pull request by crisrojas**
## 🎟️ **Jira ticket**
https://jira.tid.es/browse/SMARTWIFI-7896

## 🥅 **What's the goal?**
Conform to Mistica Design System typography specs:
https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/fundamentals/typography

## 🚧 **How do we do it?**
Update baseSize property for presets 5 (20), 9 (40) and 10 (48)

### CODE REVIEW

**Review by josetorronteras — APPROVED** [review]

**Review by Gomay88 — APPROVED** [review]

**Comment by amegias** [comment]
there are new screenshots which are not related to the text size changes
Are they really needed?

Captura de pantalla 2023-10-18 a las 13 21 45

**Comment by crisrojas** [comment]
> there are new screenshots which are not related to the text size changes Are they really needed?
> 
> Captura de pantalla 2023-10-18 a las 13 21 45

Good question 🤔. Not sure what they were regenerated. Seems there's a minor difference in the corner radius.
Would be good if we can see the output of the CI after running the tests for see if there's a problem or not about them being regenerated, but they're stuck on the SDWebImage thing...Should I still revert them ?

**Comment by amegias** [comment]
> > there are new screenshots which are not related to the text size changes Are they really needed?
> > Captura de pantalla 2023-10-18 a las 13 21 45
> 
> Good question 🤔. Not sure what they were regenerated. Seems there's a minor difference in the corner radius. Would be good if we can see the output of the CI after running the tests for see if there's a problem or not about them being regenerated, but they're stuck on the SDWebImage thing...Should I still revert them ?

I think so, I would try to revert all of screenshots except those which were failing due to font size changes

**Comment by amegias** [comment]
Tested on my laptop. 231 files should be changed (instead of 306 🤔 )

**Review by amegias — APPROVED** [review]

**Pull request merged**
