### PR TITLE
[IOS-9386] Building with XCode 15

### PR DESCRIPTION
**Pull request by alejandroruizponce**
## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-9386

## 🥅 **What's the goal?**
Build and integrate with XCode 15 and iOS 17 now we have slaves updated with that version.

## 🚧 **How do we do it?**
Update configuration in Makefile with a new simulator iPhone 15 in iOS 17.0 and using XCode 15 app.

Compiling with XCode 15 and on iPhone 15 misaligns some tiny pixels in the snapshots which requires that many of them have been re-generated with little difference.

## 🧪 **How can I verify this?**
Check CI tests and new catalog version generated.

### CODE REVIEW

**Comment by amegias** [comment]
@alejandroruizponce where is the app? Remember to upload it in the Alpha slot
https://appcenter.ms/orgs/Tuenti-Organization/apps/Mistica-SwiftUI-iOS

**Review by DavidMarinCalleja — APPROVED** [review]
Looks good to me, but I just have a question, do you think it is in our interest to add a tolerance margin to avoid uploading images that are actually almost identical?

**Comment by amegias** [comment]
> Looks good to me, but I just have a question, do you think it is in our interest to add a tolerance margin to avoid uploading images that are actually almost identical?

It won't solve this kind of PRs :( since you record the test and the result is different (new screenshot needs to be commited :()
I would avoid testing for all brands in some cases which are not interesting

**Comment by alejandroruizponce** [comment]
> @alejandroruizponce where is the app? Remember to upload it in the Alpha slot https://appcenter.ms/orgs/Tuenti-Organization/apps/Mistica-SwiftUI-iOS

Ok, now it's uploaded in alpha. I had uploaded it in enterprise instead.

**Review by amegias — APPROVED** [review]

**Pull request merged**
