### PR TITLE
IOS-10636 add new font weight to vivo type

### PR DESCRIPTION
**Pull request by L-Trujillo26**
> [!WARNING]
> Should a designer need to review/verify this PR?

## 🎟️ **Jira ticket**
https://jira.tid.es/browse/IOS-10636

## 🥅 **What's the goal?**
Add new font weight to vivo type in novum and mistica catalog

## 🚧 **How do we do it?**
Added font file to Xcode project.
Added new UIAppFonts entry in info.plist.
Usage  the font for VivoNew interface in BrandStyle+FontMapping.swift

## 🧪 **How can I verify this?**
Select the VivoNew brand.
Navigate to the Fonts tab in the Mistica Catalog. Verify that the medium fonts have been updated to the new font.

viveTypeMediumAfter

### CODE REVIEW

**Review by dhidalgofadrique — APPROVED** [review]
Good job!

**Review by aweell — APPROVED** [review]

**Comment by DavidMarinCalleja** [comment]
@L-Trujillo26  I've relaunched the "Record screenshots" GA because it is failing but it failed in the last step: "Set last commit status" please, could you take a look?

**Comment by L-Trujillo26** [comment]
> @L-Trujillo26 I've relaunched the "Record screenshots" GA because it is failing but it failed in the last step: "Set last commit status" please, could you take a look?

It seems to be an issue with the runner

**Review by DavidMarinCalleja — APPROVED** [review]

**Pull request merged**
