### PR TITLE
IOS-7865 Update movistar mistica color palette for digital hub. Remov…

### PR DESCRIPTION
**Pull request by idenjoe**
## 🎟️ **Jira ticket**
[IOS-7865](https://jira.tid.es/browse/IOS-7865) Update Movistar brand color palette

## 🥅 **What's the goal?**
Update the Movistar color palette with the latest version of [Mistica-design](https://github.com/Telefonica/mistica-design/blob/production/tokens/movistar.json) color palette.

## 🚧 **How do we do it?**

1. Removed all the tokens and colors in MovistarColorPalette to add from zero the updated ones. 
2. Renamed in MisticaColor protocol those tokens that had changed their name.
3. Removed unused O2Classic palette and assets.
4. Removed backgroundBrandGradient token because it was only used by FeedbackView->GradientView in O2Classic. The rest of the brands used a solid color.
5. Removed GradientView.

## 🏑 **AppCenter build**

qr

### CODE REVIEW

**Review by amegias — COMMENTED** [review]
There are many screenshots related to o2classic yet
Screenshot 2023-03-07 at 09 41 24

**Comment by idenjoe** [comment]
> There are many screenshots related to o2classic yet
> Screenshot 2023-03-07 at 09 41 24

Good catch. Thx!

**Review by alejandroruizponce — APPROVED** [review]
Good refactor!

**Review by amegias — APPROVED** [review]

**Review by yceballost — APPROVED** [review]

**Pull request merged**
