### PR TITLE
IOS-9848 Add new TU brand

### PR DESCRIPTION
**Pull request by franciscojrp**
## 🎟️ **Jira ticket**
[IOS-9848](https://jira.tid.es/browse/IOS-9848) [Mistica] Support for Tu brand

## 🥅 **What's the goal?**
Add support for the new TU brand that is already defined in [mistica-design](https://github.com/Telefonica/mistica-design/blob/production/tokens/tu.json)

## 🚧 **How do we do it?**
- Add the new TU brand to the Makefile
- Execute `make skin ref=production` 
- Add the new brand to Mistica Catalog app
- Add the new screenshot test references

## 🧪 **How can I verify this?**
Simulator Screenshot - iPhone 15 Pro - 2024-02-27 at 10 05 44

## 🏑 **AppCenter build**
image

### CODE REVIEW

**Review by idenjoe — APPROVED** [review]
Good job! IMHO I think you should add someone to the PR from the design team.

**Review by alejandroruizponce — APPROVED** [review]
Good work!

**Comment by yceballost** [comment]
I can't download the app with this QR! Can you generate a public link for that? thanks! 🙏

**Review by yceballost — APPROVED** [review]
awesome!

**Pull request merged**
