### PR TITLE
IOS-8073 Update textSecondaryInverse for all brands

### PR DESCRIPTION
**Pull request by dhidalgofadrique**
## 🎟️ **Jira ticket**
[IOS-8073](https://jira.tid.es/browse/IOS-8073) Update textSecondaryInverse for all brands

## 🥅 **What's the goal?**
Update textSecondaryInverse (light mode) for all brands:

Movistar: movistarBlue10 (already using this color)
Movistar Classic: movistarBlue10 (no longer used)
Vivo: vivoPurpleLight20 (it was using white)
O2: o2BluePrimary15 (it was using white)
O2Classic: o2SkyBlueLight20 (no longer used)
Blau: blauBluePrimary20 (it was using white)
Telefónica: telefonicaBlue10 (no longer used)
Solar360: movistarBlue10 -> No changed for now. Opened [IOS-1800](https://jira.tid.es/browse/OMNI-1800) ticket 

## 🚧 **How do we do it?**
Changed colors for light mode
Added new test to generate header with inverse style to be able to test this change

## 🧪 **How can I verify this?**
You can use the next build:
https://install.appcenter.ms/orgs/Tuenti-Organization/apps/Mistica-SwiftUI-iOS/distribution_groups/public
Version 23.2.0 (1)
Apr 19, 2023 at 09:13

And check textSecondaryInverse colors <b><i>in light mode</i></b>

### CODE REVIEW

**Comment by dhidalgofadrique** [comment]
> LGTM! Since it's a visual change, add a designer to confirm the changes please.

Right, I didn't realize

**Review by AnaMontes11 — APPROVED** [review]
Nice job!

**Review by DavidMarinCalleja — APPROVED** [review]
Good job1

**Pull request merged**
